/*
 * This source file was generated by the Gradle 'init' task
 */
package org.mario;

import org.mario.game.Game;

public class App {

    private static Game game = new Game();

    public String getGreeting() {
        return "Hello Walid!";
    }

    public static void main(String[] args) {
        game.init();
    }
}
